spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testebackend
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  h2:
    console:
      enabled: false